name: Release RPFramework

on:
    push:
        tags:
            - "v*"

permissions:
    contents: write

jobs:
    build:
        runs-on: windows-2022

        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: Install .NET
              uses: actions/setup-dotnet@v5
              with:
                  dotnet-version: 10.0.x
                  include-prerelease: true

            - name: Download Dalamud
              run: |
                  Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/latest.zip -OutFile dalamud.zip
                  Expand-Archive -Force dalamud.zip "$env:AppData\XIVLauncher\addon\Hooks\dev"

            - name: Build
              run: dotnet build SamplePlugin/SamplePlugin.csproj --configuration Release

            - name: Package
              run: |
                  $src = (Get-ChildItem -Path "SamplePlugin/bin" -Recurse -Directory | Where-Object { $_.FullName -match '[/\\]Release' } | Select-Object -First 1 -ExpandProperty FullName)
                  Write-Host "Checking output directory:"
                  Get-ChildItem -Path $src -Recurse
                  if (-not (Test-Path $src)) {
                    Write-Error "Output directory $src does not exist!"
                    exit 1
                  }
                  Compress-Archive -Path (Join-Path $src '*') -DestinationPath latest.zip -Force

            - name: Create GitHub Release
              uses: softprops/action-gh-release@v2
              with:
                  files: latest.zip
                  generate_release_notes: true
